### ISSUE TITLE
Styling: Brand Styling

### ISSUE THREAD

**Issue by matthew-ia** [matthew-ia/greenlife#3]
Set em up in `_variables.scss` before we start implementing specific brand styling (i.e. buttons, typography, etc.)

---
**UPDATE 2019.3.13:**

### To Do:
- [x] Add Woodford Bourne as a local resource in `pub/`
- [x] Resize icons
- [x] Resize logotype (add Family Farms?)
- [x] Style links
- [x] Style images to have border radius (bleed at edge?)
  - [x] Also make them larger
- [x] Finish button styling
- [x] Make size of p text in Header larger
- [x] Make size of H2 larger
- [x] Make Purple Heart Homes logo smaller
- [x] Make size of H3 larger
- [x] Make font size of primary footer larger
- [x] Make font size of secondary footer smaller

**UPDATE 2019.3.15**
- [x] change email link to match wireframe (white with underline)

**Comment by mgluf** [comment]
I added all of the colors and started to add the fonts. Not sure the best way to add all the woodford fonts since those are local but I at least added the Bold version.
