### ISSUE TITLE
Content: images and icons

### ISSUE THREAD

**Issue by matthew-ia** [matthew-ia/greenlife#4]
# We Need Content! (But we kinda already have it all)

Need to get exports of all the images on the site, including icons. All of these images should be in `1-Design/Website/_resc/` except the card icons which need to be exported from the XD Wireframe file. The Header image also has a few opacity layers on it to give it the color effect in the Wireframe, but we could take the raw file and edit in Photoshop to make it look better (or simply group and export directly from the XD file).

### Here's a list of all the images we need:
- [x] **Header image** (blue sky/corn field)
- [x] **Info card icons** (When, Where, Tickets)
- [x] **Event Details arrow**
- [x] **Live music section image**
- [x] **Yoga section image**
- [x] **Family Fun section image** (`#other-list`)
- [x] **Twenty-Six Acres Brewing Co. logo**
- [x] **Purple Heart Homes logo**

**Comment by mgluf** [comment]
I decided to just resize all the images to the same size in photoshop instead of having to mess too much with styling code. Feel free to revert back to the original images if you want too have the different sizes.
