### ISSUE TITLE
Styling: Tweaks for mobile

### ISSUE THREAD

**Issue by matthew-ia** [matthew-ia/greenlife#6]
For the most part I think the site will translate pretty well to mobile. The info sections might need to stack the images on top of the text, and just center align everything maybe. Not sure. I think we should do everything else and then just tweak it for mobile with breakpoints. 

I think mobile is important for this site since it will be used as an advertisement essentially. 

---
**UPDATE 2019.3.12:**

### To Do:
- [x] Fix card styling so they stack on mobile

**UPDATE 2019.3.12:**

- [x] Fix #7 
- [x] Check for more fixes to be made

**Comment by mgluf** [comment]
The Header section seems to be the area that needs the most changes when brought into a mobile resolution. The Info Cards don't push the rest of the content down and overlaps on top of the lower content. Other than that it seems to translate fairly well.
