### ISSUE TITLE
Laptop Resolution Support

### ISSUE THREAD

**Issue by mgluf** [matthew-ia/greenlife#7]
Issues with medium resolution laptops on the info cards.

Ex. 1280 x 630 laptop displays the info cards incorrectly.

**Comment by matthew-ia** [comment]
Can you screenshot and markup the issue you're seeing? I don't see anything on the chrome dev tool responsive layout, but that can be buggy sometimes. 

**_Edit_**: Unless you just mean you think it should be horizontally laid out like on full desktop vs stacked?

![chrome dev tools 1280x630](https://user-images.githubusercontent.com/17885141/54481250-cabf8c80-4808-11e9-9ae5-cb3d1df7f003.png)
